baseurl      = "https://1ikeadragon.github.io/"
title        = "Reverse engineering blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"

  # Subtitle for home
  homeSubtitle = "  Documenting curiosity."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false


  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false
  enableThemeToggle = true
  # Metadata mostly used in document's head
  description = "Reverse engineering blog leaning towards Windows and Game Security"
  keywords = "homepage, blog"
  images = [""]

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/whydoyoucare/"

[[params.social]]
  name = "github"
  url = "https://github.com/1ikeadragon"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/whydoyoucare"

[[params.social]]
  name = "discord"
  url = "xnu53x"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[author]
  name = "1ikeadragon"


languageCode = 'en-us'

[languages]
  [languages.en]
    title = "Reverse engineering blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

#   [languages.en.params]
#     subtitle  = "basic blog"

    [languages.en.params.logo]
      logoText = "1@pwn#:"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
enableRobotsTXT = false
enableGitInfo   = false
enableEmoji     = true
canonifyURLs = true
  # And you can even create generic menu

 [[menu.main]]
    identifier = "whoami"
    name       = "whoami"
    url        = "/whoami" 

  [[menu.main]]
    identifier = "tags"
    name       = "tags"
    url        = "/tags"
  
  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"

 
